 version: 2
 jobs:
   build:
     environment:
       - LINTR_COMMENT_BOT: 'false'

     working_directory: ~/dwapi-r

     docker:
       - image: dataworld/r-devtools

     steps:
       - checkout
       - run: mkdir build build/reports build/dist

       - run:
           name: Install mockery
           command: Rscript -e "install.packages('mockery')"

       - run:
           name: Install dwapi-r
           command: RDscript -e 'devtools::install()'

       - run:
           name: Check against devel version
           command: RDscript -e 'devtools::check()' && RDscript -e 'devtools::revdep_check(); devtools::revdep_check_print_problems()'

       - run:
           name: Check against release version
           command: Rscript -e 'devtools::check()' && Rscript -e 'devtools::revdep_check(); devtools::revdep_check_print_problems()'

       - run:
           name: Lint
           command: Rscript -e 'lintr::expect_lint_free()'

       - run:
           name: Collect test coverage stats
           command: Rscript -e 'library(covr); x <- package_coverage(); to_cobertura(x, filename = "build/reports/cobertura.xml"); coverage <- percent_coverage(x); q(status = coverage < 75);'

       - run:
           name: Build
           command: Rscript -e 'devtools::build(path = "build/dist")'

       - store_artifacts:
           path: ~/dwapi-r/build/dist
           destination: dist

       - store_artifacts:
           path: ~/dwapi-r/build/reports
           destination: reports
