 version: 2
 jobs:
   build:
     environment:
       - LINTR_COMMENT_BOT: 'false'
       - NOT_CRAN: 'true'

     working_directory: ~/dwapi-r

     docker:
       - image: rocker/tidyverse

     steps:
       - checkout
       - run: mkdir build build/reports build/dist
       - run: apt-get update && apt-get install -y qpdf

       - run:
           name: Install dwapi-r
           command: Rscript -e 'devtools::install()'

       - run:
           name: Lint
           command: Rscript -e 'lintr::expect_lint_free()'

       - run:
           name: Check against release version
           command: Rscript -e 'devtools::check()'

       - run:
           name: Collect test coverage stats
           command: Rscript -e 'x <- covr::package_coverage(); covr::to_cobertura(x, filename = "build/reports/cobertura.xml"); coverage <- covr::percent_coverage(x); q(status = coverage < 75);'

       - run:
           name: Build
           command: Rscript -e 'devtools::build(path = "build/dist")'

       - run:
           name: Check reverse dependencies
           command: Rscript -e 'devtools::revdep_check(); devtools::revdep_check_print_problems()'

       - store_artifacts:
           path: ~/dwapi-r/build/dist
           destination: dist

       - store_artifacts:
           path: ~/dwapi-r/build/reports
           destination: reports
